on:
  push:
    branches: 
      - "main"

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

name: 🔖 Create System Tags
jobs:
  build:
    name: 🔖 Bump tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create tag
      uses: kangketikonlen/base-tagging@main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_OWNER: ${{ github.event.repository.owner.name }}
        REPO_TYPE: ${{ github.event.repository.owner.type }}